### ISSUE TITLE
Есть ли уверенность, что такого рода поля в АПИ существуют ?

### ISSUE THREAD

**Issue by Taalaybek** [Subb98/VK-Publisher#2]
```
'server'        => $response['server'],
 'photos_list'   => $response['photos_list'],
'group_id'      => $response['gid'],
'album_id'      => $response['aid'],
'hash'          => $response['hash'],
'access_token'
```
Тут вы жестко ограничили использование либы, хотя предлагаете использовать кастомные переменные окружения env где можно прописать версию АПИ ВК, но дело в том что в некоторых версиях поля могут различаться

**Comment by Subb98** [comment]
Возможность изменения версии предусмотрена, прежде всего, для актуализации, а не для поддержания устаревшего кода. Вы видите объективные причины оставить возможность использования предыдущих версий API в свежей библиотеке?
